name: changelog
permissions: write-all
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_assignee.yml@1.0.6
    secrets: inherit
    with:
      branch: 'master'
