name: 'Terraform GitHub Actions'
on:
  pull_request:
    branches:
      - master
jobs:
  fmt:
    name: 'terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terraform Format'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'fmt'

  default:
    name: 'default'
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for  default'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/default

      - name: 'Terraform validate for default'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/default

      - name: 'Terraform plan for generate certificate dns'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/default
  multi-region:
    name: 'multi-region'
    needs: fmt
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terraform init for multi-regionl'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example/multi-region

      - name: 'Terraform validate for multi-region'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example/multi-region

      - name: 'Terraform plan for multi-region'
        uses: 'clouddrove/github-actions@v7.0'
        with:
          actions_subcommand: 'plan'
          tf_actions_working_dir: ./_example/multi-region

  pre-commit:
    name: 'Pre-Commit'
    needs:
      - fmt
      - DNS
      - Email
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Install Tflint'
        run: |
          curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: 'Pre-Commit 🔎'
        uses: pre-commit/action@v2.0.3
        continue-on-error: true


      - name: 'Pre-Commit 🔎'
        uses: pre-commit/action@v2.0.3
        continue-on-error: true

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
