name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-checks-default-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.4
    with:
      working_directory: './examples/default/'
  tf-checks-multi-region-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.4
    with:
      working_directory: './examples/multi-region/'
