name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  default:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.5
    with:
      working_directory: './_example/default/'
  multi-region:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.5
    with:
      working_directory: './_example/multi-region/'
