name: tf-lint
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_assignee.yml@1.0.6
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
